apiVersion: v1 # cria o service account
kind: ServiceAccount
metadata:
  name: server

---

apiVersion: rbac.authorization.k8s.io/v1 # cria a role
kind: Role
metadata:
  name: server-read
rules:
- apiGroups: [""]
  resources: ["pods","services"]
  verbs: ["get","watch","list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get","watch","list"] 

---

apiVersion: rbac.authorization.k8s.io/v1 # aplcia o vinculo no service account
kind: RoleBinding
metadata:
  name: server-read-bind
subjects:
- kind: ServiceAccount
  name: server
  namespace: prod
roleRef:
  kind: Role
  name: server-read
  apiGroup: rbac.authorization.k8s.io